CREATE TABLE DISTRIBUIDOR (
    DISTRIBUIDOR_ID  INTEGER NOT NULL,
    NOME             VARCHAR(255) NOT NULL,
    CNPJ             VARCHAR(14) NOT NULL
);

ALTER TABLE DISTRIBUIDOR ADD CONSTRAINT PK_DISTRIBUIDOR PRIMARY KEY (DISTRIBUIDOR_ID);