CREATE TABLE NEGOCIACAO (
    NEGOCIACAO_ID      INTEGER NOT NULL,
    PRODUTOR_ID        INTEGER NOT NULL,
    DISTRIBUIDOR_ID    INTEGER NOT NULL,
    VALOR_TOTAL        NUMERIC(15,3) NOT NULL,
    DATA_CADASTRO      TIMESTAMP NOT NULL,
    DATA_APROVACAO     TIMESTAMP,
    DATA_CONCLUSAO     TIMESTAMP,
    DATA_CANCELAMENTO  TIMESTAMP,
    STATUS             VARCHAR(10) DEFAULT 'PENDENTE' NOT NULL
);

ALTER TABLE NEGOCIACAO ADD CONSTRAINT PK_NEGOCIACAO PRIMARY KEY (NEGOCIACAO_ID);

ALTER TABLE NEGOCIACAO ADD CONSTRAINT FK_NEG_DISTRIBUIDOR FOREIGN KEY (DISTRIBUIDOR_ID) REFERENCES DISTRIBUIDOR (DISTRIBUIDOR_ID);
ALTER TABLE NEGOCIACAO ADD CONSTRAINT FK_NEG_PRODUTOR FOREIGN KEY (PRODUTOR_ID) REFERENCES PRODUTOR (PRODUTOR_ID);

ALTER TABLE NEGOCIACAO ADD CONSTRAINT CK_NEG_STATUS CHECK (STATUS IN ('PENDENTE', 'APROVADA', 'CONCLUIDA','CANCELADA'));
ALTER TABLE NEGOCIACAO ADD CONSTRAINT CK_NEG_TOTAL CHECK (VALOR_TOTAL >= 0);
