
CREATE TABLE PRODUTOR_DISTRIBUIDOR_CREDITO (
    CREDITO_ID       INTEGER NOT NULL,
    PRODUTOR_ID      INTEGER NOT NULL,
    DISTRIBUIDOR_ID  INTEGER NOT NULL,
    LIMITE_CREDITO   NUMERIC(15,3) NOT NULL,
    DATA_CADASTRO    TIMESTAMP NOT NULL,
    DATA_ALTERACAO   TIMESTAMP
);

ALTER TABLE PRODUTOR_DISTRIBUIDOR_CREDITO ADD CONSTRAINT PK_PRODUTOR_DISTRIBUIDOR_CREDIT PRIMARY KEY (CREDITO_ID);
ALTER TABLE PRODUTOR_DISTRIBUIDOR_CREDITO ADD CONSTRAINT FK_CRED_DISTRIBUIDOR FOREIGN KEY (DISTRIBUIDOR_ID) REFERENCES DISTRIBUIDOR (DISTRIBUIDOR_ID);
ALTER TABLE PRODUTOR_DISTRIBUIDOR_CREDITO ADD CONSTRAINT FK_CRED_PRODUTOR FOREIGN KEY (PRODUTOR_ID) REFERENCES PRODUTOR (PRODUTOR_ID);

ALTER TABLE PRODUTOR_DISTRIBUIDOR_CREDITO ADD CONSTRAINT CK_CRED_LIMITE CHECK ((LIMITE_CREDITO >= 0));

ALTER TABLE PRODUTOR_DISTRIBUIDOR_CREDITO ADD CONSTRAINT UK_CRED_PROD_DIST UNIQUE (PRODUTOR_ID, DISTRIBUIDOR_ID);
