CREATE GENERATOR GEN_PRODUTOR_ID;

CREATE TABLE PRODUTOR (
    PRODUTOR_ID  INTEGER NOT NULL,
    NOME         VARCHAR(255) NOT NULL,
    "CPF/CNPJ"   VARCHAR(15) NOT NULL,
    ATIVO        VARCHAR(1) NOT NULL
);

ALTER TABLE PRODUTOR ADD CONSTRAINT CK_ATIVO CHECK (ATIVO IN ('S','N'));
ALTER TABLE PRODUTOR ADD CONSTRAINT PK_PRODUTOR PRIMARY KEY (PRODUTOR_ID);

