
CREATE TABLE NEGOCIACAO_ITEM (
    NEGOCIACAO_ITEM_ID  INTEGER NOT NULL,
    NEGOCIACAO_ID       INTEGER NOT NULL,
    PRODUTO_ID          INTEGER NOT NULL,
    QTD                 NUMERIC(15,3) NOT NULL,
    PRECO_UNITARIO      NUMERIC(15,3) NOT NULL,
    VALOR_TOTAL         NUMERIC(15,3) NOT NULL
);


ALTER TABLE NEGOCIACAO_ITEM ADD CONSTRAINT PK_NEGOCIACAO_ITEM PRIMARY KEY (NEGOCIACAO_ITEM_ID);



ALTER TABLE NEGOCIACAO_ITEM ADD CONSTRAINT FK_ITEM_NEGOCIACAO FOREIGN KEY (NEGOCIACAO_ID) REFERENCES NEGOCIACAO (NEGOCIACAO_ID);
ALTER TABLE NEGOCIACAO_ITEM ADD CONSTRAINT FK_NEG_ITEM_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (PRODUTO_ID);

ALTER TABLE NEGOCIACAO_ITEM ADD CONSTRAINT CK_QTDE CHECK (QTD > 0);
ALTER TABLE NEGOCIACAO_ITEM ADD CONSTRAINT CK_ITEM_PRECO CHECK (PRECO_UNITARIO >= 0);
ALTER TABLE NEGOCIACAO_ITEM ADD CONSTRAINT CK_VALOR_TOTAL CHECK (VALOR_TOTAL >= 0);

ALTER TABLE NEGOCIACAO_ITEM ADD CONSTRAINT UK_ITEM_PRODUTO UNIQUE (NEGOCIACAO_ID, PRODUTO_ID);




