
CREATE TABLE PRODUTO (
    PRODUTO_ID      INTEGER NOT NULL,
    NOME            VARCHAR(255) NOT NULL,
    PRECO_UNITARIO  NUMERIC(15,3) NOT NULL
);

ALTER TABLE PRODUTO ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (PRODUTO_ID);