SET TERM ^ ;

create or alter procedure SP_APROVAR_NEGOCIACAO (
    P_NEGOCIACAO_ID integer)
as
declare variable V_PRODUTOR_ID integer;
declare variable V_DISTRIBUIDOR_ID integer;
declare variable V_STATUS varchar(10);
declare variable V_QTDE_ITENS integer;
declare variable V_VALOR_NEGOCIACAO numeric(15,3);
declare variable V_LIMITE_CREDITO numeric(15,3);
declare variable V_TOTAL_APROVADO numeric(15,3);
BEGIN
  V_PRODUTOR_ID = NULL;
  V_DISTRIBUIDOR_ID = NULL;
  V_STATUS = NULL;

  SELECT
      PRODUTOR_ID,
      DISTRIBUIDOR_ID,
      STATUS
  FROM NEGOCIACAO
  WHERE NEGOCIACAO_ID = :P_NEGOCIACAO_ID
  WITH LOCK
  INTO
      :V_PRODUTOR_ID,
      :V_DISTRIBUIDOR_ID,
      :V_STATUS;

  IF (V_PRODUTOR_ID IS NULL) THEN
    EXCEPTION EX_NEG_NAO_ENCONTRADA;

  IF (V_STATUS <> 'PENDENTE') THEN
    EXCEPTION EX_NEG_STATUS_INVALIDO;

  SELECT
      COUNT(*),
      COALESCE(SUM(QTD * PRECO_UNITARIO), 0)
  FROM NEGOCIACAO_ITEM
  WHERE NEGOCIACAO_ID = :P_NEGOCIACAO_ID
  INTO
      :V_QTDE_ITENS,
      :V_VALOR_NEGOCIACAO;

  IF (V_QTDE_ITENS = 0) THEN
    EXCEPTION EX_NEG_SEM_ITENS;

  UPDATE NEGOCIACAO_ITEM
  SET VALOR_TOTAL = CAST((QTD * PRECO_UNITARIO) AS NUMERIC(15,3))
  WHERE NEGOCIACAO_ID = :P_NEGOCIACAO_ID;

  V_LIMITE_CREDITO = NULL;

  SELECT
      LIMITE_CREDITO
  FROM PRODUTOR_DISTRIBUIDOR_CREDITO
  WHERE PRODUTOR_ID = :V_PRODUTOR_ID
    AND DISTRIBUIDOR_ID = :V_DISTRIBUIDOR_ID
  WITH LOCK
  INTO :V_LIMITE_CREDITO;

  IF (V_LIMITE_CREDITO IS NULL) THEN
    EXCEPTION EX_CREDITO_NAO_CADASTRADO;

  SELECT
      COALESCE(SUM(I.QTD * I.PRECO_UNITARIO), 0)
  FROM NEGOCIACAO N
  JOIN NEGOCIACAO_ITEM I ON I.NEGOCIACAO_ID = N.NEGOCIACAO_ID
  WHERE N.PRODUTOR_ID = :V_PRODUTOR_ID
    AND N.DISTRIBUIDOR_ID = :V_DISTRIBUIDOR_ID
    AND N.STATUS = 'APROVADA'
    AND N.NEGOCIACAO_ID <> :P_NEGOCIACAO_ID
  INTO :V_TOTAL_APROVADO;

  IF ((V_TOTAL_APROVADO + V_VALOR_NEGOCIACAO) > V_LIMITE_CREDITO) THEN
    EXCEPTION EX_LIMITE_INSUFICIENTE;

  UPDATE NEGOCIACAO
  SET
      STATUS = 'APROVADA',
      VALOR_TOTAL = :V_VALOR_NEGOCIACAO,
      DATA_APROVACAO = CURRENT_TIMESTAMP,
      DATA_CONCLUSAO = NULL,
      DATA_CANCELAMENTO = NULL
  WHERE NEGOCIACAO_ID = :P_NEGOCIACAO_ID;
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT,UPDATE ON NEGOCIACAO TO PROCEDURE SP_APROVAR_NEGOCIACAO;
GRANT SELECT,UPDATE ON NEGOCIACAO_ITEM TO PROCEDURE SP_APROVAR_NEGOCIACAO;
GRANT SELECT ON PRODUTOR_DISTRIBUIDOR_CREDITO TO PROCEDURE SP_APROVAR_NEGOCIACAO;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE SP_APROVAR_NEGOCIACAO TO SYSDBA;
