SET TERM ^ ;

create or alter procedure SP_CONCLUIR_NEGOCIACAO (
    P_ID_NEGOCIACAO integer)
as
declare variable V_STATUS varchar(10);
BEGIN
  V_STATUS = NULL;

  SELECT
      STATUS
  FROM NEGOCIACAO
  WHERE NEGOCIACAO_ID = :P_ID_NEGOCIACAO
  WITH LOCK
  INTO :V_STATUS;

  IF (V_STATUS IS NULL) THEN
    EXCEPTION EX_NEG_NAO_ENCONTRADA;

  IF (V_STATUS <> 'APROVADA') THEN
    EXCEPTION EX_NEG_CONCLUIR_INVALIDA;

  UPDATE NEGOCIACAO
  SET
      STATUS = 'CONCLUIDA',
      DATA_CONCLUSAO = CURRENT_TIMESTAMP,
      DATA_CANCELAMENTO = NULL
  WHERE NEGOCIACAO_ID = :P_ID_NEGOCIACAO;
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT,UPDATE ON NEGOCIACAO TO PROCEDURE SP_CONCLUIR_NEGOCIACAO;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE SP_CONCLUIR_NEGOCIACAO TO SYSDBA;