CREATE SEQUENCE GEN_NEGOCIACAO_ITEM_ID;
ALTER SEQUENCE GEN_NEGOCIACAO_ITEM_ID RESTART WITH 0;

/* Old syntax is:
CREATE GENERATOR GEN_NEGOCIACAO_ITEM_ID;
SET GENERATOR GEN_NEGOCIACAO_ITEM_ID TO 0;
*/
