SET SQL DIALECT 3;


CREATE GENERATOR GEN_DISTRIBUIDOR_ID;

SET TERM ^ ;



CREATE OR ALTER TRIGGER BI_DISTRIBUIDOR_ID FOR DISTRIBUIDOR
ACTIVE BEFORE INSERT POSITION 0
AS
begin
IF ((NEW.DISTRIBUIDOR_ID IS NULL) OR (NEW.DISTRIBUIDOR_ID = 0)) THEN
    NEW.DISTRIBUIDOR_ID = GEN_ID(GEN_DISTRIBUIDOR_ID, 1);
end
^
SET TERM ; ^
