SET SQL DIALECT 3;


CREATE GENERATOR GEN_NEGOCIACAO_ID;

SET TERM ^ ;



CREATE OR ALTER TRIGGER BI_NEGOCIACAO_ID FOR NEGOCIACAO
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  IF ((NEW.NEGOCIACAO_ID IS NULL) OR (NEW.NEGOCIACAO_ID = 0)) THEN
    NEW.NEGOCIACAO_ID = GEN_ID(GEN_NEGOCIACAO_ID, 1);
end
^
SET TERM ; ^
