SET SQL DIALECT 3;


CREATE GENERATOR GEN_NEGOCIACAO_ITEM_ID;

SET TERM ^ ;



CREATE OR ALTER TRIGGER BI_NEGOCIACAO_ITEM_ID FOR NEGOCIACAO_ITEM
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    IF ((NEW.NEGOCIACAO_ITEM_ID IS NULL) OR (NEW.NEGOCIACAO_ITEM_ID = 0)) THEN
    NEW.NEGOCIACAO_ITEM_ID = GEN_ID(GEN_NEGOCIACAO_ITEM_ID, 1);
end
^
SET TERM ; ^
