SET SQL DIALECT 3;


CREATE GENERATOR GEN_PRODUTO_ID;

SET TERM ^ ;



CREATE OR ALTER TRIGGER BI_PRODUTO_ID FOR PRODUTO
ACTIVE BEFORE INSERT POSITION 0
AS
begin
   IF ((NEW.PRODUTO_ID IS NULL) OR (NEW.PRODUTO_ID = 0)) THEN
    NEW.PRODUTO_ID = GEN_ID(GEN_PRODUTO_ID, 1);
end
^
SET TERM ; ^
