SET SQL DIALECT 3;


CREATE GENERATOR GEN_PRODUTOR_ID;

SET TERM ^ ;



CREATE OR ALTER TRIGGER BI_PRODUTOR_ID FOR PRODUTOR
ACTIVE BEFORE INSERT POSITION 0
AS
begin
 IF ((NEW.PRODUTOR_ID IS NULL) OR (NEW.PRODUTOR_ID = 0)) THEN
    NEW.PRODUTOR_ID = GEN_ID(GEN_PRODUTOR_ID, 1);
end
^
SET TERM ; ^
