SET SQL DIALECT 3;


CREATE GENERATOR GEN_CREDITO_ID;

SET TERM ^ ;



CREATE OR ALTER TRIGGER CREDITO_ID FOR PRODUTOR_DISTRIBUIDOR_CREDITO
ACTIVE BEFORE INSERT POSITION 0
AS
begin
   IF ((NEW.CREDITO_ID IS NULL) OR (NEW.CREDITO_ID = 0)) THEN
    NEW.CREDITO_ID = GEN_ID(GEN_CREDITO_ID, 1);
end
^
SET TERM ; ^
